version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-runtime:
        patterns: ["*"]
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      container:
        patterns: ["*"]
    open-pull-requests-limit: 2
